version: '3.8'

services:
  oracle:
    image: container-registry.oracle.com/database/free:23.3.0.0
    container_name: oracle23c
    environment:
      - ORACLE_PWD=${ORACLE_PWD}
    ports:
      - "1521:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./init.sql:/opt/oracle/scripts/startup/init.sql:ro

    healthcheck:
      test: ["CMD", "bash", "-c", "echo 'SELECT 1 FROM DUAL;' | sqlplus -L sys/${ORACLE_PWD}@localhost:1521/FREEPDB1 as sysdba > /dev/null || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3

volumes:
  oracle_data:
